name: Export Framer Sites to HTML

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/40 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  export-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install HTTrack
        run: sudo apt-get install -y httrack

      - name: Export Main Framer Site
        run: |
          echo "Downloading main site... in arabic"
          httrack "https://semat.framer.website/ar" -O ./main_site --mirror --keep-alive --depth=2 --clean
          # Sync the downloaded files to the repository root
          if [ -d "./main_site/semat.framer.website" ]; then
            rsync -a ./main_site/semat.framer.website/ ./
          fi
          rm -rf ./main_site

      - name: Export Arabic Framer Site
        run: |
          echo "Downloading Arabic site..."
          httrack "https://semat.framer.website/" -O ./en_site --mirror --keep-alive --depth=2 --clean
          mkdir -p ./en
          # Sync the downloaded files to the /en directory
          if [ -d "./en_site/semat.framer.website/en" ]; then
            rsync -a ./en_site/semat.framer.website/en/ ./en/
          fi
          rm -rf ./en_site

      - name: Commit and Push Changes
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Automated update of exported Framer sites"
            git push https://x-access-token:${{ secrets.ACTIONS_PAT }}@github.com/${{ github.repository }}.git HEAD:main
          fi
